### ISSUE TITLE
Some errors are not forwarded to R

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#54]
E.g. when there's a dependency resolution error:

```
Install system packages as root...
Package R-CRAN-sf available, but not installed.
Traceback (most recent call last):
  File "/usr/share/R/library/CoprManager/service/CoprManager.py", line 149, in <module>
    run_as_root(args)
  File "/usr/share/R/library/CoprManager/service/CoprManager.py", line 124, in run_as_root
    pkgs = call_backend(args.cmd, pkgs, root=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/R/library/CoprManager/service/CoprManager.py", line 33, in call_backend
    return getattr(backend, cmd)(PREF, pkgs, EXCL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/R/library/CoprManager/service/backend/dnf.py", line 60, in install
    base.resolve()
  File "/usr/lib/python3.11/site-packages/dnf/base.py", line 929, in resolve
    raise exc
dnf.exceptions.DepsolveError: 
 Problem: conflicting requests
  - nothing provides libgdal.so.31()(64bit) needed by R-CRAN-sf-1.0.9-1.fc38.copr5027045.x86_64
```

**Comment by eddelbuettel** [comment]
Do you think one can/should catch that?

**Comment by Enchufa2** [comment]
Now I see:

```r
> install.packages("sf")
Install system packages as root...
Error: cannot connect to the system package manager
```

I want to see:

```r
> install.packages("sf")
Install system packages as root...
Error: Package R-CRAN-sf available, but not installed.
 Problem: conflicting requests
  - nothing provides libgdal.so.31()(64bit) needed by R-CRAN-sf-1.0.9-1.fc38.copr5027045.x86_64
```

**Comment by Enchufa2** [comment]
It works in D-Bus mode, but not in root mode.
